### PR TITLE
Add README.md for the stream-* files - DO NOT USE

### PR DESCRIPTION
**Pull request by richb-hanover**
I found it difficult to figure out how to make the examples work, so I wrote these READMEs. In addition, I fixed a few typos and Lint'ed the files so there are fewer Javascript questions.

Please review my descriptions to be sure they're accurate. 

Also, feel free to aggregate these changes into a single commit. Thanks!

Rich

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
cool!

**Comment by hemanth** [comment]
Could you please squash the commits?

**Comment by richb-hanover** [comment]
@hemanth Sorry - my git fu isn't strong enough. (and I see why it would have been great to do it had I known how to do it before I pushed the commits to github...) Is this something I can do now that they're on my github fork?

**Comment by hemanth** [comment]
Definitely, checkout [squashing with rebase.](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

**Comment by richb-hanover** [comment]
Thanks for the pointer. I think I screwed things up pretty badly. I can't say for certain, but I think it's because I edited some files locally, and some from github. I'm getting this error:

richs-mbp-10715:KoaJSExamples richb$ git rebase -i HEAD-4
fatal: Needed a single revision
invalid upstream HEAD-4

I plan to delete my fork on github, re-clone to my local system then apply the the changes and re-send a pull request... (there are only four folders that changed...)

Best,

Rich

**Comment by richb-hanover** [comment]
Done. I've issued a new pull request to replace this one

**Comment by hemanth** [comment]
Yikes..`git rebase -i HEAD~4` it's tilde not `-` :+1:

**Pull request closed without merging**
